services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:13-alpine           # Используем официальный образ PostgreSQL
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build:
      dockerfile: Dockerfile.alembic
      context: .
    volumes:
      - ./app/alembic:/tgbot/app/alembic    # монтируем в ту же папку, куда копировали
      - ./alembic.ini:/tgbot/alembic.ini    # аналогично для конфига
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    
volumes:
  postgres_data: