# Используем тот же базовый образ, что и для основного бота
FROM python

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt alembic asyncpg

# Копируем необходимые файлы
COPY alembic.ini .
COPY app/db.py ./app/
COPY app/models.py ./app/
COPY app/alembic ./app/alembic

# Добавляем текущую директорию в PYTHONPATH
ENV PYTHONPATH=/app

CMD ["sh", "-c", "alembic upgrade head && tail -f /dev/null"]